# Generated by Django 5.2.9 on 2026-01-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='industry_type',
            field=models.CharField(choices=[('ecommerce', 'E-commerce'), ('fintech', 'Fintech'), ('healthcare', 'Healthcare'), ('edtech', 'EdTech'), ('real_estate', 'Real Estate'), ('logistics', 'Logistics'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
