# Generated by Django 5.2.9 on 2026-01-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='question_generation_prompt',
            field=models.TextField(blank=True, default='You are an AI assistant for getting the project requirements from the client.\nFollowing are the predefined and AI asked questions along with their answers (if available).\nPlease ask relevant questions to get the complete requirements from the client based on the below questions and answers if any are missing.\nPlease provide only the list of questions semicolon separated that need to be asked to the client to get the complete project requirements. Do not include any other text.'),
        ),
        migrations.AddField(
            model_name='settings',
            name='requirement_generation_prompt',
            field=models.TextField(blank=True, default="You are an AI assistant for generating project requirements in HTML format that should be visually stunning. Include:\n• Project overview\n• Detailed functional requirements\n• Technical requirements\n• User stories\n• Acceptance criteria\n• Wireframe descriptions (text)\n• Database schema suggestions\n• API endpoint list\n\nExcludes:\n• User flow diagrams\n• Timeline\n• Costing\n\nBased on the client's answers to the questions asked, please generate a comprehensive project requirement to be presented to the client."),
        ),
    ]
