# Generated by Django 5.2.9 on 2026-01-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_pendingregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('CEO', 'CEO'), ('CTO', 'CTO'), ('Developer', 'Developer'), ('Project Manager', 'Project Manager'), ('Other', 'Other'), ('client', 'Client')], default='Other', max_length=50),
        ),
    ]
